// Use https://finicky-kickstart.now.sh to generate basic configuration
// Learn more about configuration options: https://github.com/johnste/finicky/wiki/Configuration

// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",
  options: {
    // Hide the finicky icon from the top bar. Default: false
    hideIcon: false, 
    // Check for update on startup. Default: true
    checkForUpdate: true,
    // Change the internal list of url shortener services. Default: undefined
    urlShorteners: (list) => [
      ...list, 
      "https://deu01.safelinks.protection.outlook.com/"
    ],
    // Log every request with basic information to console. Default: false
    logRequests: false
  },   
  handlers: [
    {
      match: /^https?:\/\/google\.com\/.*$/,
      browser: "Safari"
    },
    {
      match: /^https?:\/\/.*\.office\.com\/.*$/,
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: /^https?:\/\/.*\.azure\.com\/.*$/,
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: /^https?:\/\/.*\.realmjoin\.com\/.*$/,
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: /^https?:\/\/c4a8\.odoo\.com\/.*$/,
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: /^https?:\/\/gitlab\.c4a8\.net\/.*$/,
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: /^https?:\/\/.*\.sharepoint\.com\/.*$/,
      browser: "/Applications/Microsoft Edge.app"
    },
    { 
      match: "*https%3A%2F%2Fglueckkanja.hire.trakstar.com*",
      browser: "/Applications/Microsoft Edge.app"
    },
    { 
      match: "*https%3A%2F%2Fdev.azure.com*",
      browser: "/Applications/Microsoft Edge.app"
    },
    { 
      match: "*c4a8.odoo.com*",
      browser: "/Applications/Microsoft Edge.app"
    },
    { 
      match: "*gitlab.c4a8.net*",
      browser: "/Applications/Microsoft Edge.app"
    },
    { 
      match: "*outlook.office.com*",
      browser: "/Applications/Microsoft Edge.app"
    },
    { 
      match: "*github.com*",
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: "*sharepoint.com*",
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: "*c4a8.personio.de*",
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: "*c4a8.net*",
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: "*app.gitbook.com*",
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: "*tasks.office.com*",
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: "*eu.docusign.net*",
      browser: "/Applications/Microsoft Edge.app"
    },
    {
      match: /l\/meetup-join|l\/channel/,
      browser: 'com.microsoft.teams',
      url({ url }) {
        return {
          ...url,
          protocol: 'msteams',
        };
      },
    },   
    {
      // Open links in Safari when the option key is pressed
      // Valid keys are: shift, option, command, control, capsLock, and function.
      // Please note that control usually opens a tooltip menu instead of visiting a link
      match: () => finicky.getKeys().option,
      browser: "/Applications/Microsoft Edge.app"
    }
    //{ 
    //  match: /^https?:\/\/teams\.microsoft\.com\/l\/meetup\-join\/.*$/,
    //  browser: "Microsoft Teams"
    //},
    // https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fredirect-url.email%2F%3Flink%3Dhttps%253A%252F%252Fc4a8.odoo.com%252Fmail%252Fview%253Fmodel%253Dsale.order%2526res_id%253D2532%26apn%3Dcom.odoo.mobile%26afl%3Dhttps%253A%252F%252Fc4a8.odoo.com%252Fmail%252Fview%253Fmodel%253Dsale.order%2526res_id%253D2532%26ibi%3Dcom.odoo.mobile%26ifl%3Dhttps%253A%252F%252Fc4a8.odoo.com%252Fmail%252Fview%253Fmodel%253Dsale.order%2526res_id%253D2532&data=05%7C01%7Cgerrit.reinke%40glueckkanja-gab.com%7C2a8a20bb56514e492ff808da332be64f%7Ca53834b742bc46a3b004369735c3acf9%7C0%7C0%7C637878560939817352%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wZ1rGWinN7iFqt6f7BniuYcg4EmMUYyqVyAPrKvZSDo%3D&reserved=0
    // https://teams.microsoft.com/l/meetup-join/19%3ameeting_YWRjMTM0ZjktNGExOS00NjY5LWFjOGUtZWE0MzkyZjFmMjA2%40thread.v2/0?context=%7b%22Tid%22%3a%22a53834b7-42bc-46a3-b004-369735c3acf9%22%2c%22Oid%22%3a%22e8449119-c130-4036-8246-ffdf06a7511e%22%7d  
    // https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZDFjZGVlZTUtODNhYS00ZTMxLWFlNjUtYmJlYjk4OTE0M2Nk%40thread.v2/0?context=%7b%22Tid%22%3a%22a53834b7-42bc-46a3-b004-369735c3acf9%22%2c%22Oid%22%3a%22e8449119-c130-4036-8246-ffdf06a7511e%22%7d
  ]
}